development:
  adapter: postgresql
  encoding: unicode
  database: sci_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sci_test
  pool: 5
  username:
  password: 

